### ISSUE TITLE
Hair style similarity calculation

### ISSUE THREAD

**Issue by kexul** [FusionBrainLab/HairFastGAN#1]
Dear Authors:
    Thanks for your greate work! I'm interested in clustering some of my pictures using your pretrained network by extracting the hairstyle features, is that feasible? I've tried using a CLIP model to describe the hairstyle but it's not accurate enough.

Many thanks!

**Comment by maximkm** [comment]
Hello,
Thank you for interest in our work! Regrettably, our model may not be suitable for the task of clustering. However, I would recommend considering the [CtrlHair method](https://github.com/XuyangGuo/CtrlHair). This approach is capable of representing a given hairstyle through independent normal values that correspond to various hair characteristics, such as color, shape, and texture. Given these features, I believe it could potentially be utilized for clustering purposes.

**Comment by kexul** [comment]
Thanks for your recommendation.
