### ISSUE TITLE
hairstyle manipulation

### ISSUE THREAD

**Issue by 123456klk1** [FusionBrainLab/HairFastGAN#18]
Hello, I wanted to start by saying that your work is outstanding, and I’m really looking forward to seeing your future research.

I have a question I’d like to ask for your advice on. My current goal is to focus solely on hairstyle manipulation, so I set the hair colour path to None, but I didn’t get the expected results. I was wondering if you have any suggestions or insights on this?

**Comment by maximkm** [comment]
Hello! Thank you for your kind words about our work. We truly appreciate your interest and support.

Regarding your question about hairstyle manipulation, I can clarify the issue you're experiencing. The method interface doesn't accept "None" as a valid input for the color_path. To maintain the original hair color of the hairstyle, you need to explicitly set the color_path to be the same as the face_path.

Here's an example of arguments in command:

```
--face_path=1.png --shape_path=42.png --color_path=1.png
```

In this case, using the same image for both face_path and color_path ensures that the original hair color is preserved while allowing for shape manipulation.

I hope this explanation helps clarify the process. If you have any further questions or need additional assistance, please don't hesitate to ask.

**Comment by 123456klk1** [comment]
I get it! Thank you very much for your reply.
