### ISSUE TITLE
can HairFastGAN run on windows?

### ISSUE THREAD

**Issue by nirvanaYu777** [FusionBrainLab/HairFastGAN#2]
We see that the requirements show that a Linux system is required. Can it run on a Windows system?

**Comment by maximkm** [comment]
Hello,

Thank you for your question! While the code has not been specifically tested on Windows, there doesn’t appear to be anything that would inherently prevent it from functioning on this platform. However, please note that the commands provided in the installation section are not compatible with PowerShell. Therefore, you would need to adapt them or proceed with a manual installation. As an alternative, I would suggest considering the use of the [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install).

I hope this helps! Please let me know if you have any other questions.

**Comment by Hewesag57** [comment]
Thank you for your reply! We'll test on windows ASAP.
