### ISSUE TITLE
Do I need to download the entire FFHQ dataset？

### ISSUE THREAD

**Issue by Wenwen717** [FusionBrainLab/HairFastGAN#7]
Thank you for sharing such excellent work！
I am currently generating data according to your data production script. However, I noticed that the FFHQ dataset is very large. Could you please tell me which files within it are essential?

<img width="878" alt="image" src="https://github.com/AIRI-Institute/HairFastGAN/assets/43174767/4be77700-ec61-4af3-9c5d-f4f9bc161862">

**Comment by maximkm** [comment]
Hello,
To train the model, you need to download images from the FFHQ dataset with a size of 1024x1024 (89.1GB).
In our research, we utilized all 70,000 images, but if you prefer a smaller subset, downloading around 10,000 images should be sufficient.
