### ISSUE TITLE
How to convert pre-trained HairFast model into ONNX format.

### ISSUE THREAD

**Issue by Gnort1002** [FusionBrainLab/HairFastGAN#8]
Thank you very much for creating such a wonderful repository like this! 
Following the instructions in the README.md, I was able to smoothly run the repo, but is there a way to use the HairFast model in ONNX format? 
Once again, I would like to thank you for your great work. I hope to receive a prompt response from the authors.

**Comment by maximkm** [comment]
Hello,
currently, our pipeline involves applying several different neural networks, which are connected by Python code. Converting this pipeline to ONNX format might be challenging. As of now, the only option seems to be manually converting all the networks to ONNX.

In our future work, we will explore the possibility of fusing all the networks to improve efficiency and enable compatibility with ONNX.
